"use client";

import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";
import { initAuth, login } from "rakesh-ds-common/auth";
import { useEffect } from "react";
const SlButton = dynamic(
  () => import("rakesh-wc-design-system/dist/react/button"),
  { ssr: false }
);

export default function Home() {
  const consoleThis = () => {
    login({ email: "test@test.com", password: "test" });
  };

  useEffect(() => {
    initAuth({
      apiBaseUrl: "https://redrob-ai-backend-development.up.railway.app",
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>chat app </h1>
        <SlButton onClick={consoleThis}>login </SlButton>
      </main>
    </div>
  );
}
