"use client";

import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";
import { initAuth, login, getUserProfile } from "rakesh-ds-common/auth";

import "rakesh-ds-common/components";

import { useEffect } from "react";
const SlButton = dynamic(
  () => import("rakesh-wc-design-system/dist/react/button"),
  { ssr: false }
);

const RedrobNavbar = dynamic(() => import("rakesh-ds-common/components"), {
  ssr: false,
});

export default function Home() {
  const consoleThis = async () => {
    try {
      const response = await login({
        email: "rakesh.gupta+124@mckinleyrice.co",
        password: "Rakesh@123",
      });
      console.log("response is ", response);
    } catch (error) {
      console.log("error is ", error);
    }
  };

  useEffect(() => {
    initAuth({
      apiBaseUrl: "http://localhost:5000",
    });
  }, []);
  let authenticated = true;
  let user = { email: "test@test.com", name: "rakesh" };
  let loading = false;
  const navLinks = [{ label: "Home", href: "/" }];

  const footerLinks = [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms of Service", href: "/terms" },
    { label: "Contact", href: "/contact" },
  ];

  const socialLinks = [
    { platform: "Twitter", href: "https://twitter.com/yourapp" },
    { platform: "GitHub", href: "https://github.com/yourapp" },
    { platform: "LinkedIn", href: "https://linkedin.com/company/yourapp" },
  ];

  const getUserProfileDetails = async () => {
    try {
      const response = await getUserProfile();
      console.log("response is ", response);
    } catch (error) {
      console.log("error is ", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <redrob-navbar
        title="My App"
        logo="/logo.png"
        links={JSON.stringify(navLinks)}
      >
        <div
          slot="actions"
          style={{ display: "flex", gap: "1rem", alignItems: "center" }}
        >
          {authenticated ? (
            <>
              <span style={{ color: "white" }}>Welcome, {user?.email}</span>
              <button
                onClick={() => console.log("called the log out ")}
                disabled={loading}
                style={{
                  padding: "0.5rem 1rem",
                  backgroundColor: "#dc2626",
                  color: "white",
                  border: "none",
                  borderRadius: "0.375rem",
                  cursor: "pointer",
                  fontWeight: "500",
                }}
              >
                {loading ? "Logging out..." : "Logout"}
              </button>
            </>
          ) : (
            <button
              onClick={() =>
                document.getElementById("login-modal")?.classList.add("show")
              }
              disabled={loading}
              style={{
                padding: "0.5rem 1rem",
                backgroundColor: "#2563eb",
                color: "white",
                border: "none",
                borderRadius: "0.375rem",
                cursor: "pointer",
                fontWeight: "500",
              }}
            >
              Login
            </button>
          )}
        </div>
      </redrob-navbar>
      <main className={styles.main}>
        <h1>chat app </h1>
        <SlButton onClick={consoleThis}>login </SlButton>

        <SlButton onClick={getUserProfileDetails}>get user details </SlButton>
      </main>

      <redrob-footer
        copyright="© 2024 My App. All rights reserved."
        links={JSON.stringify(footerLinks)}
        socialLinks={JSON.stringify(socialLinks)}
        show-user
      >
        <div slot="brand">
          <h3 style={{ color: "white", marginBottom: "0.5rem" }}>My App</h3>
          <p style={{ fontSize: "0.875rem" }}>
            Building amazing things together
          </p>
        </div>
        <div slot="extra">
          <p style={{ fontSize: "0.875rem" }}>
            Need help? <a href="/support">Contact Support</a>
          </p>
        </div>
      </redrob-footer>
    </div>
  );
}
